services:
 mongo-beoordelingen:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_beoordeling_data:/data/db
    
 mysql-boeking:
  image: mysql:latest
  ports:
    - 3305:3306
  volumes:
    - mysql_boeking_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-catalogus:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_catalogus_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 mysql-profiel:
  image: mysql:latest
  ports:
    - 3309:3306
  volumes:
    - mysql_profiel_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 beoordeling-service:
  depends_on:
    - mongo-beoordelingen
  image: vsensodyne/beoordelingsservice
  ports:
    - 8083:8083
  links:
    - mongo-beoordelingen
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-beoordelingen
   
 catalogusservice:
  depends_on:
    - mysql-catalogus
  image: vsensodyne/catalogusservice
  ports:
    - 8082:8082
  links:
    - mysql-catalogus
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-catalogus
   MYSQL_DB_PORT: 3307

 profielservice:
  depends_on:
    - mysql-profiel
  image: vsensodyne/profielservice
  ports:
    - 8080:8080
  links:
    - mysql-profiel
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-profiel
   MYSQL_DB_PORT: 3309 

 boekingservice:
  depends_on:
    - catalogusservice
  image: vsensodyne/boekingservice
  ports:
    - 8081:8081
  links:
    - catalogusservice
  environment:
   CATALOGUS_INFO_SERVICE_BASEURL: catalogusservice:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-boeking
   MYSQL_DB_PORT: 3305


volumes:
 mongodb_beoordeling_data:
 mysql_catalogus_data:
 mysql_boeking_data:
 mysql_profiel_data:
