server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: boeking-service-post
          uri: http://${BOEKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/boekingen
            - Method=POST
          filters:
            - SetPath=/api/boeking
        - id: boeking-service-get
          uri: http://${BOEKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/boekingen
            - Method=GET
          filters:
            - SetPath=/api/boeking
        - id: boeking-service-put
          uri: http://${BOEKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/boekingen/{boekingNummer}
            - Method=PUT
          filters:
            - SetPath=/api/boeking/{boekingNummer}
        - id: boeking-service-delete
          uri: http://${BOEKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/boekingen/{boekingNummer}
            - Method=DELETE
          filters:
            - SetPath=/api/boeking/{boekingNummer}
        - id: profiel-service-get
          uri: http://${PROFIEL_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/profielen
            - method=GET
          filters:
            - SetPath=/api/profiel
        - id: catalogus-service-get
          uri: http://${CATALOGUS_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/catalogussen
            - Method=GET
          filters:
            - SetPath=/api/catalogus

